name: Deploy Backend with Compose
on:
  push:
    # Cumplimos con el requisito de la pauta: usar la rama deploy
    branches: [ "deploy" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_BACK_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Dar permisos a Docker
            sudo chmod 666 /var/run/docker.sock
            
            # 2. Limpiar carpeta anterior y clonar la rama deploy
            sudo rm -rf Back_Eval2
            git clone -b deploy https://github.com/ignaciokort/Back_Eval2.git
            cd Back_Eval2
            
            # 3. Crear archivo .env al vuelo para que el Compose lo use
            # Esto es más seguro y profesional
            echo "DB_HOST=${{ secrets.DB_HOST }}" > .env
            echo "DB_USER=root" >> .env
            echo "DB_PASSWORD=admin" >> .env
            echo "DB_NAME=proyecto_db" >> .env
            echo "PORT=3000" >> .env
            
            # 4. Levantar todo con Docker Compose
            # -d: segundo plano, --build: reconstruye la imagen del back
            docker-compose down
            docker-compose up -d --build
